[tools]
rojo = { source = "Roblox/rojo-rbx-rojo", version = "6.2.0" }
selene = { source = "Roblox/Kampfkarren-selene", version = "0.25.0" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "0.17.1" }
rotrieve = { source = "Roblox/rotriever", version = "0.5.13-alpha.3" }
lest = { source = "Roblox/lest", version = "3.9.0" }
