[package]
name = "Cryo"
authors = ["Roblox"]
license = "MIT"
content_root = "src"
version = "1.1.0"
files = ["*", "!*.spec.lua"]

[config]
registry_index = true

[dev_dependencies]
TestEZ = "github.com/Roblox/testez@0.4.1"
